blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/that-github-user/thinktank/discussions
    about: Ask questions and discuss ideas here instead of opening an issue
